# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory: ~
        fos_userbundle:
                    id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider # Use form.csrf_provider instead for Symfony <2.4
                login_path: /auth/login
                check_path: fos_user_security_check
                failure_path: /auth
            logout:
                path: /auth/logout
                target: /auth
#            logout:       true
            anonymous:    true
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
            - { path: ^/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/auth/register, role: ROLE_USER }
            - { path: ^/auth/resetting, role: ROLE_USER }
            - { path: ^/auth/, role: ROLE_USER }
            - { path: ^/create, role: ROLE_USER }
            - { path: ^/category/create, role: ROLE_USER }
            - { path: ^/all, role: ROLE_USER }
            - { path: ^/edit, role: ROLE_USER }
#            - { path: ^/category, role: ROLE_USER }
            - { path: ^/auth/profile/, role: ROLE_USER }
            - { path: ^/auth/profile/edit, role: ROLE_USER }
            - { path: ^/auth/register/, role: ROLE_USER }
            - { path: ^/auth/profile/change-password, role: ROLE_USER }
            - { path: ^/slide, role: ROLE_USER }
            - { path: ^/menu, role: ROLE_USER }
